<a href="https://colab.research.google.com/github/lytcool369/tensorflow2.0/blob/master/03_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_2_0_%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 3.7 난수 얻기(균일 분포)
import tensorflow as tf
import matplotlib.pyplot as plt

rand = tf.random.uniform([1], 0, 1)
print(rand)

tf.Tensor([0.7353165], shape=(1,), dtype=float32)


In [ ]:
# 3.8 난수 여러개 얻기 (균일 분포)
rand = tf.random.uniform([4], 0, 1)
print(rand)

tf.Tensor([0.42317748 0.69271445 0.41266823 0.5442978 ], shape=(4,), dtype=float32)


In [ ]:
# 3.9 난수 얻기 (정규 분포)
rand = tf.random.normal([4], 0, 1)
print(rand)

tf.Tensor([ 0.5251804 -0.537773  -1.2567564 -0.9572656], shape=(4,), dtype=float32)


In [ ]:
# 3.10 시그모이드 함수
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [ ]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1], 0, 1)
output = sigmoid(x * w)
print(output)

0.34597366229057075


In [ ]:
# 3.12 경사 하강법을 이용한 뉴런의 학습
x = 1
y = 0
w = tf.random.normal([1], 0, 1)

for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error

  if i % 100 == 99:
    print(i, error, "\t", output)

99 -0.11287153944474228 	 0.11287153944474228
199 -0.05519632716631186 	 0.05519632716631186
299 -0.03610887030799743 	 0.03610887030799743
399 -0.026738707422745457 	 0.026738707422745457
499 -0.021198683557359134 	 0.021198683557359134
599 -0.017547125678997855 	 0.017547125678997855
699 -0.01496214573748289 	 0.01496214573748289
799 -0.013037383045468453 	 0.013037383045468453
899 -0.011549234980887585 	 0.011549234980887585
999 -0.010364634525544125 	 0.010364634525544125


In [ ]:
# x=0, y=1일 때, y=1을 얻는 뉴런의 학습

In [ ]:
# 3.14 뉴런의 학습에 편향을 더함
x = 0
y = 1
w = tf.random.normal([1], 0, 1)
b = tf.random.normal([1], 0, 1)

for i in range(1000):
  output = sigmoid(x * w + 1 * b)
  error = y - 